#!/usr/bin/env bash

cachename="tmenu_path"
fullpath="$XDG_CACHE_HOME/$cachename"

if [ ! -f "$cachename" ]; then
    echo "$PATH" | tr ':' '\n' | while read -r dir; do
        [ -d "$dir" ] && find "$dir" -maxdepth 1 -type f -executable -printf '%p\n' 2>/dev/null
    done | sort -u > "$fullpath"
fi

PROG=$(tmenu < "$fullpath")
SUCCESS=$?

if [ "$SUCCESS" -ne 0 ]; then
    exit 1
fi

# sh -c "$PROG" >/dev/null 2>&1 & disown
setsid sh -c "$PROG" >/dev/null 2>&1 &
sleep 0.1
